package org.mgellert.aoc2025.day07

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.mgellert.aoc2025.readInput

class LaboratoriesTest {

    @Test
    fun testPart1() {
        val input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().split("\n")
        val splits = Laboratories().part1(input)
        assertEquals(21, splits)
    }

    @Test
    fun solvePart1() {
        val splits = Laboratories().part1(readInput("day07.txt"))
        assertEquals(1609, splits)
    }

    @Test
    fun testPart2() {
        val input = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent().split("\n")
        val count = Laboratories().part2(input)
        assertEquals(40, count)
    }

    @Test
    fun solvePart2() {
        val splits = Laboratories().part2(readInput("day07.txt"))
        assertEquals(12472142047197L, splits)
    }
}